version: '3.4'

services:
  db:
    container_name: vending_machine
    image: postgres:latest
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - vending_machine:/var/lib/postgresql/data

volumes:
  vending_machine:
    name: vending_machine